# Source language and JDK version to use.
language: java
jdk: oraclejdk7

# Get files for use with build, namely the custom Maven settings.xml.
before_install:
  - "git clone https://github.com/Q0rDev/travis-ci-resources.git target/travis"
  - "git clone https://github.com/Q0rDev/q0rdev-javadocs.git -b gh-pages target/doxy"
  - "chmod +x target/travis/build.sh"
  - "chmod +x target/travis/upload.sh"
  - "chmod +x target/travis/doxy.sh"

# Compile and package JAR and set build properties.
install: true
script: ./target/travis/build.sh

# Upload to DBO if release build / Upload to AWS always / Create Doxy files.
after_success:
  - "./target/travis/upload.sh"
  - "./target/travis/doxy.sh"

# Upload to AWS Always
after_failure:
  - "./target/travis/upload.sh"

notifications:
  # Disable build status email notifications, until the issue with forks is fixed.
  email: false
  webhooks:
    # Send build information and status to Notifico.
    - http://n.tkte.ch/h/3746/XtPhEL8P_VVjJwrOz9kZwjw2

env:
  global:
    # Nexus Deployment
    - secure: "aBQCpWRVId+DbSzyAzlBYM9vg4WSG3nKitNebgmi197uyDpeZdDsiAIVtwfT9uB2gg8tzDIs9JI4k+weSdLw2Wk8Pu0+9XRhVEPmZ5JuniDspdnnalONyKir43YENKHvqSnB6QHysKjc8VgEVJNeP/MbZxLFMl2bJj0SehEGx7w="
    # GitHub
    - secure: "Utu0CGOt0n/gmgQ+2vqsxAktc01Ig4f/44xdENPEzugd5IKSB/NPcqYl3coCzU4tNe18+YGG/gCtrxluunxy4OeYBtVrUclE8XuhYWiXO2WmUACyvXOSW4BbkGSxtWUPlU7d+imGaywDhdnIlG/cbzCMIq9o8buDF1f1b2Vv050="
    # AWS
    - secure: "PO1fucnNAYo1nPecF28G8INDYl7R4nMw1JHrEoAMuN8/iionpoGn1u9yP+Vd9MX6uiZHVCgQEUp43g9TUDyj7EGkt0ZGJdEM/lXHauP2lc1vCj7/Cn3vqfBbETGAfwOxRNW4iY9wiX81MqYWI1DT5zGMBdPhKyrXOqM+NQLhXG0="